name: dragontiger
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flip_card: ^0.7.0


  cupertino_icons: ^1.0.2

  shimmer: ^3.0.0
  add_to_cart_animation: ^2.0.3
  google_fonts: ^5.1.0
  upi_india: ^3.0.1
  just_audio: ^0.9.29
  provider: ^6.0.3
  simple_ripple_animation: ^0.0.3
  http:



dev_dependencies:
  flutter_test:
    sdk: flutter






flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/cards/
    - assets/chips/
    - assets/image/
    - assets/buttons/
    - assets/background/
    - assets/companylogo/
    - assets/images/crown/
    - assets/images/dice/
    - assets/images/
    - assets/sounds/





